### PR TITLE
273 tests

### PR DESCRIPTION
**Pull request by shramee**
Addresses https://github.com/Shard-Labs/starknet-hardhat-plugin/pull/297#issuecomment-1400314191

Pipeline fails because the contract is not declared.

### CODE REVIEW

**Comment by shramee** [comment]
WRT https://github.com/Shard-Labs/starknet-hardhat-plugin/pull/297#issuecomment-1400314191

Fixed, my bad I just tried to deploy a contract which wasn't declared. 😳 🙊

**Comment by FabijanC** [comment]
@shramee I set the target branch to `plugin` as this is the branch used by the plugin in its tests (only after releasing a new plugin version do we set branch `master` to `plugin` in this example repo). But still, some old commits are attempting to be merged (probably because you used the same branch as for the previous PR). You can either reset your branch to only contain the last commit or create a new PR from a new branch.

**Comment by shramee** [comment]
I'll do the former, should be easier with fewer conflicts.

**Comment by shramee** [comment]
Done in #95

**Pull request closed without merging**
